site_name: Minecraft Guides
site_author: HoppinHauler
strict: true

theme:
  name: material
  language: ru
  font:
    text: Nunito
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - content.tooltips
    - toc.follow
  palette:
    - scheme: slate
      primary: black
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Светлая тема
    - scheme: default
      primary: black
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Темная тема

extra_css:
  - assets/mc.css

extra_javascript:
  - assets/mc.js

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Главная: index.md
  - Modern Industrialization:
      - "Этап 1. Пар и бронза": modern-industrialization/stage-01.md
