site_name: Minecraft Guides
site_author: HoppinHauler

theme:
  name: material
  language: ru
  features:
    - navigation.sections
    - navigation.top
    - toc.follow
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Тёмная тема
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Светлая тема

extra_css:
  - assets/mc.css

extra_javascript:
  - assets/mc.js

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Главная: index.md
  - Modern Industrialization:
      - "Этап 1. Пар и бронза": modern-industrialization/stage-01.md
