site_name: Minecraft Guides
site_author: HoppinHauler
site_url: https://beinforit.github.io/mcguides-site/
strict: true
copyright: >-
  Текст гайда: HoppinHauler,
  <a href="https://creativecommons.org/licenses/by-sa/4.0/deed.ru">CC BY-SA 4.0</a>.
  Текстуры и иконки принадлежат Mojang и авторам модов.
  Не официальный продукт Minecraft, сайт не связан с Mojang, Microsoft и All the Mods.

exclude_docs: |
  /en/

theme:
  name: material
  language: ru
  font:
    text: Nunito
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - content.tooltips
    - toc.follow
  palette:
    - scheme: slate
      primary: black
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Светлая тема
    - scheme: default
      primary: black
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Темная тема

extra:
  alternate:
    - name: Русский
      link: ./
      lang: ru
    - name: English
      link: en/
      lang: en

extra_css:
  - assets/mc.css

extra_javascript:
  - assets/mc.js

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Главная: index.md
  - Modern Industrialization:
      - "Этап 1. Пар и бронза": modern-industrialization/stage-01.md
